/*
 * Last Updated: 0/0/2017
 * Class description:
 */
package winratemachine;

import java.awt.event.ActionListener;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Pussy Whisperer
 */
public class WRView extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form WRView
     * @throws java.io.IOException
     */
    public WRView() throws IOException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMain = new javax.swing.JPanel();
        buttonWin = new javax.swing.JButton();
        buttonLoss = new javax.swing.JButton();
        lableWinCounter = new javax.swing.JLabel();
        lableLossCounter = new javax.swing.JLabel();
        buttonCalculate = new javax.swing.JButton();
        lableCalculateWinRate = new javax.swing.JLabel();
        buttonWinSubtract = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonWin.setText("Win");
        buttonWin.addActionListener(this);

        buttonLoss.setText("Loss");
        buttonLoss.addActionListener(this);

        lableWinCounter.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lableWinCounter.setText("0");

        lableLossCounter.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lableLossCounter.setText("0");

        buttonCalculate.setText("Calculate WinRate");
        buttonCalculate.addActionListener(this);

        lableCalculateWinRate.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lableCalculateWinRate.setText("0");

        buttonWinSubtract.setText("-");
        buttonWinSubtract.addActionListener(this);

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(buttonWinSubtract)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lableWinCounter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                .addComponent(lableLossCounter)
                .addGap(187, 187, 187))
            .addGroup(panelMainLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(buttonCalculate)
                        .addGap(18, 18, 18)
                        .addComponent(lableCalculateWinRate))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addComponent(buttonWin)
                        .addGap(121, 121, 121)
                        .addComponent(buttonLoss)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lableLossCounter)
                    .addComponent(lableWinCounter)
                    .addComponent(buttonWinSubtract))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonWin)
                    .addComponent(buttonLoss))
                .addGap(51, 51, 51)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCalculate)
                    .addComponent(lableCalculateWinRate))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == buttonWin) {
            WRView.this.buttonWinActionPerformed(evt);
        }
        else if (evt.getSource() == buttonLoss) {
            WRView.this.buttonLossActionPerformed(evt);
        }
        else if (evt.getSource() == buttonCalculate) {
            WRView.this.buttonCalculateActionPerformed(evt);
        }
        else if (evt.getSource() == buttonWinSubtract) {
            WRView.this.buttonWinSubtractActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculateActionPerformed
        double wc = Integer.parseInt(this.lableWinCounter.getText());
        double lc = Integer.parseInt(this.lableLossCounter.getText());
        double total = wc + lc;
        double calc = wc / total;
        this.lableCalculateWinRate.setText(calc + "");
    }//GEN-LAST:event_buttonCalculateActionPerformed

    private void buttonWinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWinActionPerformed
        winCounter = winCounter += 1;
        this.lableWinCounter.setText("" + winCounter);
    }//GEN-LAST:event_buttonWinActionPerformed

    private void buttonLossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLossActionPerformed
        lossCounter = lossCounter += 1;
        this.lableLossCounter.setText("" + lossCounter);
    }//GEN-LAST:event_buttonLossActionPerformed

    private void buttonWinSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWinSubtractActionPerformed
         
    }//GEN-LAST:event_buttonWinSubtractActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WRView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WRView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WRView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WRView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new WRView().setVisible(true);
            } catch (IOException ex) {
                Logger.getLogger(WRView.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalculate;
    private javax.swing.JButton buttonLoss;
    private javax.swing.JButton buttonWin;
    private javax.swing.JButton buttonWinSubtract;
    private javax.swing.JLabel lableCalculateWinRate;
    private javax.swing.JLabel lableLossCounter;
    private javax.swing.JLabel lableWinCounter;
    private javax.swing.JPanel panelMain;
    // End of variables declaration//GEN-END:variables
    
    // Manual variable declaration   
    int winCounter;
    int lossCounter;
}   // End of Manual variable declaration
